### PR TITLE
Update services.yml for SF3+ compatibility

### PR DESCRIPTION
**Pull request by Aziule**
Added quotes to services references for SF3+ compatibility

### CODE REVIEW

**Comment by jdecool** [comment]
👍 

Wait for test results

**Comment by delphiki** [comment]
Shouldn't those be single quotes instead of double ones?

**Comment by jdecool** [comment]
Does it matter ?

Symfony use both no ?

**Comment by Aziule** [comment]
It works with both single & double quotes. I guess that choosing between the two is a question of naming conventions

**Comment by delphiki** [comment]
I mostly see single quotes for services, but that's fine. LGFM

**Comment by jdecool** [comment]
@Aziule Could you rebase this PR ?

**Pull request closed without merging**
